language: android
jdk: oraclejdk7

android:
    components:
        - build-tools-21.1.2
        - android-19

        - extra-google-google_play_services
        - extra-android-support
        - extra-play-services-map
        - extra-google-m2repository
        - extra-android-m2repository
        - addon-google_apis-google-19
